### ISSUE TITLE
Release 1588 - UI text get instead of white are difficult to read

### ISSUE THREAD

**Issue by NenuSB** [sle118/squeezelite-esp32#319] opened 2023-09-30 09:58 UTC
The label text are not visibile with update 1588.
Mainly on the Wifi and NVS pages, both in Firefox and Chrome. 

This was OK in 1539.

![image](https://github.com/sle118/squeezelite-esp32/assets/146478490/2ed0c4c6-0100-4bef-9a50-6210f9f53a98)

**Comment by sle118** [comment] 2023-09-30 12:56
@NenuSB when opening a new issue, please follow the provided template as much as possible as it provides information we need upfront. For example, the template explains how to get the logs, which is critical in troubleshooting.

But in this case, it appears that the issue is the color set rather than something backend, so logs wouldn't help that much. I'll look into this. The labels are visible, except that are black over dark grey.

**Comment by sle118** [comment] 2023-09-30 13:34
I don't have a quick fix for this. for now I recommend rolling back the version until I resolve the issue.

**Comment by sle118** [comment] 2023-10-01 20:39
This release, https://github.com/sle118/squeezelite-esp32/commit/f87b3adec2f13dc343f75207f0938b10dd52cab0, should fix the text color issue.

**Closed as completed by sle118** 2023-10-01 20:39 UTC
Labels: bug
