### ISSUE TITLE
ESP_ERR_NVS_KEY_TOO_LONG, when trying to enter wifi ssid and password

### ISSUE THREAD

**Issue by DamnDaniel-98** [sle118/squeezelite-esp32#412] opened 2024-04-14 09:34 UTC
Whenever I try to enter my Wifi data via the web interface, the EPS first connects to the Wifi. However, the message: "_[PlaceholderForMySSID]_ (error) ESP_ERR_NVS_KEY_TOO_LONG" appears in the LOGs (_[PlaceholderForMySSID]_ is a placeholder). If I then restart the ESP, it does not connect to the Wifi and starts its default AP.

The firmware was installed via the online installer under "[Squeezelite-ESP32 Installer (sle118.github.io)](https://sle118.github.io/squeezelite-esp32-installer/)" (Generic/I2S). The board is a ESP32-A1S.

**Comment by sle118** [comment] 2024-04-14 17:35
Please follow the bug template. 
 https://github.com/sle118/squeezelite-esp32/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by sle118** [comment] 2024-04-28 18:03
Possible duplicate of #410

**Closed as completed** 2024-05-15 11:44 UTC
Labels: Incomplete
