### ISSUE TITLE
Add IR RC5 Protocol and repeat function

### ISSUE THREAD

**Issue by Renber78** [sle118/squeezelite-esp32#291] opened 2023-08-26 09:24 UTC
Hi,

  I use your code and I am satisfied with it, thank you for the work!

For hardware reasons I would like to use a remote control rather than buttons (simpler mechanical level). I tested with an NEC compatible remote control, it works well except the volume buttons because there is no repeat function, is it possible to add this functionality which is supported by the LMS?

I also have a large number of remote controls but most are with the RC5 protocol. Nowadays, finding an original slimdevices remote control is mission impossible. The number of brands using the NEC protocol is quite limited (Sanyo, Fisher, Nec, Mitsubishi, ...?). Wouldn't it be interesting to add the RC5 protocol in order to support so-called "media center" remote controls? These remote controls are very popular and can be found for a few € on alliexpress. (HP media remote)

I am not able to do code for RC5 but I can provide various .ir mapping as I have a lot of stock.

What do you think ?

**Comment by philippe44** [comment] 2023-08-27 02:45
There a version( not released) being built that should handle rc5. I don't have many other remotes and it does not seem to work with my TV, so maybe it's a problem but can you try and let me know. The log is verbose enough at the moment that it will tell you scan codes

**Comment by Renber78** [comment] 2023-08-27 07:42
Thank you for the work already done since my request.
Unfortunately I have no results with various RC5 remotes, nothing appears in the logs (with an NEC it always works unless IR:rc5, normal)
If you have an RC5 remote control (Philips for example) make sure it works by pressing in front of a camera (you should see the IR led light up)

Another point, after research, it is possible that the remote controls say "media center" use the RC6 protocol ... if you could add this one too :-)

For the repeat function, have you worked on it on this build?

THANKS

**Comment by philippe44** [comment] 2023-08-27 07:48
No, rc6 is not something that I'll support. For repeat, I have to check but I'm not sure this is easy to integrate with LMS and the way I handle ir codes, so it's a bit unlikely. I'll see what I can do for rc5 but unless there is something obvious I've missed, I'm pretty out of options here

**Comment by philippe44** [comment] 2023-08-27 22:18
Repeat is handled. I don't think I have an rc5 remote, all packets I receive are 34 in length which is NEC or Pronto (AFAIU). Probably your remote are not rc5 either. I've added a log where you can see the whole received buffer so you can figure out the coding and type of IR. 

It's a byte dump organized by 16 bits packets
- take 2 bytes, the LSByte is first so swap them
- the 1st bit (MSbit) is the value read by the IR receiver, inverted
- the next 15 bits are the duration in µs of the bit
- and so on...

For example, using NEC protocol : bb 22 ee 91 is
bb 22 => 22 bb => first bit is 0 => 1, duration is 22 bb  = 8891 µs
ee 91 => 91 ee => first bit is 1 => 0, duration is 11 ee = 4590 µs

This is a proper NEC header pattern. To analyze, chatGPT can be your friend. Something like "Take each segment in hexadecimal, assemble them by 2 to form a 16 bits value. Swap bytes. Take MSB, invert it, that's value. Take 15 LSB, that's duration in µs". And be careful, chatGPT spews a lot of crap as well.

**Comment by Renber78** [comment] 2023-08-28 16:22
Thanks for the effort ;-)
I will test as soon as the build is online because I don't have the tools to compile.

**Comment by wizmo2** [comment] 2023-08-28 17:15
@philippe44.  I have a SqueezeAmp with the IR pre installed.  The latest release does not run in ota mode (reverts to recovery), and gives the following error.
```
I (2892) IR: Starting Infrared Receiver on gpio 0
E (2892) rmt: rmt_driver_install(1021): RMT driver already installed for channel
```

Had to remove the `0=ir` or add one of the new options (`:nec`) to get it to boot.

**Comment by philippe44** [comment] 2023-08-28 17:24
That's interesting, I did not have that issue and I did not change to nec or rc5 to start with. What else do you have on your set_gpio line?

**Comment by philippe44** [comment] 2023-08-28 17:33
> Thanks for the effort ;-)
> 
> I will test as soon as the build is online because I don't have the tools to compile.
>
Thé build is there but you need to manually download the binary by going to the tags and select the one you want. It is not "released" which means it will not appear in the "update" of the firmware so you need to select the downloaded file

**Comment by Renber78** [comment] 2023-08-28 17:38
but sorry I can't find binary. Can you tell me exactly where it is?
I see the 505 in tag but no bin

**Comment by wizmo2** [comment] 2023-08-28 17:47
> That's interesting, I did not have that issue and I did not change to nec or rc5 to start with. What else do you have on your set_gpio line?

just the 0=ir

Edit:  Something must have got into 2.1501, as this was with the release not a local build

**Comment by Renber78** [comment] 2023-08-28 18:04
FYI: I just did a test with the SqueezeAmp-16 (501) firmware and the same config as you (0=ir) and I had no boot problem.

**Comment by Renber78** [comment] 2023-09-05 17:01
Hi,

I'll come back to you with my RC5 tests because I finally managed to compile locally. Thanks for updating the readme (protobuf), that was my problem...

Back to the remote controls.
My observations:
- RC5 remote controls now work with the <gpio>=ir:rc5 parameter only
- Key repeat works but stuttering sound (with volume keys only)
- The <gpio>ir parameter alone only works with NEC

I think there is an adjustment to be made to the repeat function because it must take up too many CPU resources...

I also noticed that my Windows media center remote control is in RC6 and does not work, I know that you do not want to hear about this protocol but allow me to ask you to reconsider your position because these remote controls are very suitable for squezzelite and will, I think, bring a real plus to your project.

I still have to test a large number of remote controls in order to make a list of those that are currently compatible. I'll get back to you with that and probably some IR mappings

Here is a log of the st-by button on the RC6 media center remote control... just in case ;-)

<details><summary>Remote Log</summary>
<pre>
I (1247981) IR: can't decode IR signal of len 34
I (1247981) IR: ad 0a 36 83 fd 01 7a 81 fe 01 7a 81 fd 01 3f 83
I (1247981) IR: fd 01 32 83 75 05 3a 83 02 02 7e 81 02 02 7f 81
I (1247991) IR: 01 02 83 81 fd 01 83 81 fd 01 83 81 18 02 69 81
I (1247991) IR: fd 01 83 81 fd 01 83 81 fd 01 83 81 fe 01 83 81
I (1248001) IR: bd 03 7a 81 02 02 7a 81 fe 01 7a 81 fd 01 3b 83
I (1248011) IR: fd 01 83 81 fd 01 83 81 fe 01 83 81 fd 01 83 81
I (1248021) IR: bd 03 3f 83 fd 01 83 81 18 02 69 81 fd 01 83 81
I (1248021) IR: fd 01 83 81 fd 01 84 81 b9 03 7e 81 fe 01 3e 83
I (1248031) IR: e4 01 9d 81 fd 01 00 80
I (1248081) IR: can't decode IR signal of len 34
I (1248091) IR: ad 0a 36 83 01 02 76 81 02 02 7a 81 fe 01 3a 83
I (1248091) IR: fe 01 31 83 7a 05 3a 83 fd 01 83 81 17 02 6a 81
I (1248101) IR: fd 01 83 81 fd 01 83 81 fd 01 83 81 fd 01 83 81
I (1248101) IR: 02 02 7f 81 01 02 7f 81 e8 01 9d 81 fd 01 83 81
I (1248111) IR: d3 03 65 81 17 02 60 81 fd 01 7b 81 fd 01 3b 83
I (1248111) IR: e8 01 9c 81 fe 01 83 81 17 02 69 81 fd 01 83 81
I (1248131) IR: ba 03 3e 83 fe 01 83 81 fd 01 83 81 fd 01 83 81
I (1248131) IR: 17 02 6a 81 fd 01 83 81 d7 03 65 81 fd 01 3b 83
I (1248141) IR: fd 01 83 81 fd 01 00 80
</pre>
</details>

Whatever comes next, thank you for your much appreciated work.

**Comment by dfrein** [comment] 2023-09-05 17:10
I can also confirm that an update to a recent version without changing <gpio>=ir leads to a boot loop (and reflashing also required to erase flash memory). However, if I change from "0=ir" to "0=ir:nec" just before flashing to I2S-4MFlash-1524, the new builds can be flashed without further problems.

**Comment by Renber78** [comment] 2023-09-05 17:12
I notice that it is not the repeat function that is the problem but the volume setting itself (I believe that the new loudness option has something to do with it)
A lot of data is sent to the server during a volume change.

**Comment by philippe44** [comment] 2023-09-05 17:42
> I notice that it is not the repeat function that is the problem but the volume setting itself (I believe that the new loudness option has something to do with it)
> 
> A lot of data is sent to the server during a volume change.
>
Indeed when loudness is activated, there is a lot happening when changing volume (and I've already minimized it a fair bit). I don't think you will experience stuttering is loudness is disabled.

**Comment by philippe44** [comment] 2023-09-05 17:43
> I can also confirm that an update to a recent version without changing <gpio>=ir leads to a boot loop (and reflashing also required to erase flash memory). However, if I change from "0=ir" to "0=ir:nec" just before flashing to I2S-4MFlash-1524, the new builds can be flashed without further problems.
>
That's weird. I'll investigate again

**Comment by philippe44** [comment] 2023-09-05 17:51
Did you have anything else on your set_GPIO line ?

**Comment by Renber78** [comment] 2023-09-05 18:02
`I don't think you will experience stuttering is loudness is disabled.`

it is off

**Comment by dfrein** [comment] 2023-09-05 18:06
Seems to be only an issue for me with build squeezelite-esp32-master-v4.3-I2S-4MFlash-16-21522.zip, perhaps a (different) issue with this specific build? Now I tested again and when flashing today's build (21524), everything seems to be fine, both tested with 0=ir and 0=ir:nec (and nothing else in my set_GPIO line), whereas 21522 again leads to a boot loop (build 21522 only tested with 0=ir). As this build is not an official / published one, and the newer one works for me, I would now not perform any further test and consider this issue as solved.

**Comment by philippe44** [comment] 2023-09-05 18:36
> Seems to be only an issue for me with build squeezelite-esp32-master-v4.3-I2S-4MFlash-16-21522.zip, perhaps a (different) issue with this specific build? Now I tested again and when flashing today's build (21524), everything seems to be fine, both tested with 0=ir and 0=ir:nec (and nothing else in my set_GPIO line), whereas 21522 again leads to a boot loop (build 21522 only tested with 0=ir). As this build is not an official / published one, and the newer one works for me, I would now not perform any further test and consider this issue as solved.
>
What bothers me is that @wizmo2 had the same issue with another build once and after that it went away. So I'm more concerned that it is something else that happens at first time the version runs and that might be a disaster when I release it. If you try again 1522 on a line with just XX=ir, does it still crash?

**Comment by philippe44** [comment] 2023-09-05 18:39
> `I don't think you will experience stuttering is loudness is disabled.`
> 
> 
> 
> it is off
>
Or that's very weird then. Can you confirm that the logs does not say anything about equalizer being active at every volume change? Can you also try the latest build where I removed all causes of unnecessary equalizer updates?

**Comment by Renber78** [comment] 2023-09-05 18:41
```
[02:13:12.943] equalizer_process:205 EQUALIZER INDEX 0 => gain:0.00, loudness:0.00,
[02:13:12.953] equalizer_process:205 EQUALIZER INDEX 1 => gain:0.00, loudness:0.00,
[02:13:12.964] equalizer_process:205 EQUALIZER INDEX 2 => gain:0.00, loudness:0.00,
[02:13:12.976] equalizer_process:205 EQUALIZER INDEX 3 => gain:0.00, loudness:0.00,
[02:13:12.977] equalizer_process:205 EQUALIZER INDEX 4 => gain:0.00, loudness:0.00,
[02:13:12.989] equalizer_process:205 EQUALIZER INDEX 5 => gain:0.00, loudness:0.00,
[02:13:12.990] equalizer_process:205 EQUALIZER INDEX 6 => gain:0.00, loudness:0.00,
[02:13:13.001] equalizer_process:205 EQUALIZER INDEX 7 => gain:0.00, loudness:0.00,
[02:13:13.013] equalizer_process:205 EQUALIZER INDEX 8 => gain:0.00, loudness:0.00,
[02:13:13.014] equalizer_process:205 EQUALIZER INDEX 9 => gain:0.00, loudness:0.00,
[02:13:13.026] equalizer_process:210 equalizer deactivated
```
This is the version taken this very morning so it seems to me to be the last one (the number is not displayed)

**Comment by Renber78** [comment] 2023-09-05 18:55
I have the same log several times between two volume action logs and that's when the sound stutters. I think this behavior is not expected


```
I (2550920) IR: Scan Code (repeat) --- addr: 0x0019 cmd: 0x0011
[02:29:10.786] equalizer_process:205 EQUALIZER INDEX 0 => gain:0.00, loudness:0.00,
[02:29:10.788] equalizer_process:205 EQUALIZER INDEX 1 => gain:0.00, loudness:0.00,
[02:29:10.799] equalizer_process:205 EQUALIZER INDEX 2 => gain:0.00, loudness:0.00,
[02:29:10.800] equalizer_process:205 EQUALIZER INDEX 3 => gain:0.00, loudness:0.00,
[02:29:10.812] equalizer_process:205 EQUALIZER INDEX 4 => gain:0.00, loudness:0.00,
[02:29:10.813] equalizer_process:205 EQUALIZER INDEX 5 => gain:0.00, loudness:0.00,
[02:29:10.824] equalizer_process:205 EQUALIZER INDEX 6 => gain:0.00, loudness:0.00,
[02:29:10.836] equalizer_process:205 EQUALIZER INDEX 7 => gain:0.00, loudness:0.00,
[02:29:10.837] equalizer_process:205 EQUALIZER INDEX 8 => gain:0.00, loudness:0.00,
[02:29:10.848] equalizer_process:205 EQUALIZER INDEX 9 => gain:0.00, loudness:0.00,
[02:29:10.849] equalizer_process:210 equalizer deactivated
[02:29:10.925] equalizer_process:205 EQUALIZER INDEX 0 => gain:0.00, loudness:0.00,
[02:29:10.927] equalizer_process:205 EQUALIZER INDEX 1 => gain:0.00, loudness:0.00,
[02:29:10.938] equalizer_process:205 EQUALIZER INDEX 2 => gain:0.00, loudness:0.00,
[02:29:10.940] equalizer_process:205 EQUALIZER INDEX 3 => gain:0.00, loudness:0.00,
[02:29:10.951] equalizer_process:205 EQUALIZER INDEX 4 => gain:0.00, loudness:0.00,
[02:29:10.952] equalizer_process:205 EQUALIZER INDEX 5 => gain:0.00, loudness:0.00,
[02:29:10.964] equalizer_process:205 EQUALIZER INDEX 6 => gain:0.00, loudness:0.00,
[02:29:10.976] equalizer_process:205 EQUALIZER INDEX 7 => gain:0.00, loudness:0.00,
[02:29:10.978] equalizer_process:205 EQUALIZER INDEX 8 => gain:0.00, loudness:0.00,
[02:29:10.989] equalizer_process:205 EQUALIZER INDEX 9 => gain:0.00, loudness:0.00,
[02:29:10.990] equalizer_process:210 equalizer deactivated
[02:29:11.686] sendIR:94 sending IR code 190011
I (2551890) IR: Scan Code  --- addr: 0x0019 cmd: 0x0011
```

**Comment by philippe44** [comment] 2023-09-05 18:58
Are you sure it is build 1523?

**Comment by Renber78** [comment] 2023-09-05 19:02
I did: "git clone --recursive https://github.com/sle118/squeezelite-esp32.git" this morning around 8am, is this the right method?
I don't see a version number anywhere, where can I find it?

**Comment by philippe44** [comment] 2023-09-05 19:05
> I did: "git clone --recursive https://github.com/sle118/squeezelite-esp32.git" this morning around 8am, is this the right method? I don't see a version number anywhere, where can I find it?
>
Go on the GH site here https://github.com/sle118/squeezelite-esp32/actions, select the build you want (say the latest one) and scroll down till you see artifacts. Take the binary that fits your platform

**Comment by Renber78** [comment] 2023-09-05 19:16
Thanks for this tip (I've been looking for this for a long time)

As a result, I must not have had the latest version, I no longer have any stuttering now and no more log loudness.
Sorry for the waste of time.

**Comment by dfrein** [comment] 2023-09-05 19:26
Yes, it's still crashing with 522: I just tried again, and it was the same: starting with the web installer I erased the device and flashed the generic/I2S version provided with the web installer. In the next step I connected to the esp32 wifi and uploaded and committed my old configuration, performed a complete reboot (with power off), and flashed from the internal web interface squeezelite.bin, extracted from a fresh download from github actions of squeezelite-esp32-master-v4.3-I2S-4MFlash-16-21522.zip. After pressing exit recovery the device was again stuck in a boot loop. The same procedure, just with 21524, was without any problems. Please find attached my complete config, with regard to set_GPIO it's just 0=IR
[nvs_config_cirrus_1630835795341json.txt](https://github.com/sle118/squeezelite-esp32/files/12527642/nvs_config_cirrus_1630835795341json.txt)

**Comment by philippe44** [comment] 2023-09-05 19:49
> Yes, it's still crashing with 522: I just tried again, and it was the same: starting with the web installer I erased the device and flashed the generic/I2S version provided with the web installer. In the next step I connected to the esp32 wifi and uploaded and committed my old configuration, performed a complete reboot (with power off), and flashed from the internal web interface squeezelite.bin, extracted from a fresh download from github actions of squeezelite-esp32-master-v4.3-I2S-4MFlash-16-21522.zip. After pressing exit recovery the device was again stuck in a boot loop. The same procedure, just with 21524, was without any problems. Please find attached my complete config, with regard to set_GPIO it's just 0=IR
> 
> [nvs_config_cirrus_1630835795341json.txt](https://github.com/sle118/squeezelite-esp32/files/12527642/nvs_config_cirrus_1630835795341json.txt)
> 
> 
Thanks - so that is probably something else causing the boot loop because I have not modified anything wrt to IR between these release (I'll double check) but a least that gives me a hint how to reproduce

**Comment by Renber78** [comment] 2023-09-05 19:49
could be a clue:

```
E (2911) gpio: io_num=34 can only be input
E (2911) gpio: gpio_set_level(237): GPIO output gpio_num error

```
My gpio 34 is ir!

**Comment by Renber78** [comment] 2023-09-05 19:58
I flashed 522 is bootloop.
here is the log where it is blocking for me:

```
[00:01:00.014] output_init_embedded:100 init I2S/SPDIF
W (3741) DAC core: DAC does not use i2c
[00:01:00.025] output_init_i2s:324 configuring MCLK on GPIO -1
[00:01:00.026] output_init_i2s:336 invalid MCK gpio -1
E (3771) I2S: i2s_driver_install(921): I2S buffer length at most 1024 and more than 8
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
```

**Comment by dfrein** [comment] 2023-09-05 20:15
Just to be clear: it was just my initial assumption that "ir:nec" is now required. I checked again, with build 1522 both 0=ir and 0=ir:nec will lead to a boot loop (on the basis of the config file I have attached above). So indeed it has nothing to do with this specific setting ("0=ir"), but rather with this specific build.

**Comment by philippe44** [comment] 2023-09-05 20:45
oh yes, I forgot this - the 1522 has an issue with i2S. I pushed a wrong change in the middle of many other things I was doing. I'll delete it. Sorry for the mess

**Comment by philippe44** [comment] 2023-09-06 01:28
> I also noticed that my Windows media center remote control is in RC6 and does not work, I know that you do not want to hear about this protocol but allow me to ask you to reconsider your position because these remote controls are very suitable for squezzelite and will, I think, bring a real plus to your project.
> 
That's a good opportunity to do some C 😄. RC6 is here https://pcbheaven.com/userpages/The_Philips_RC6_Protocol/ and you can use the services/infrared.c code that I've updated to support NEC and RC5 as a good start base!

**Comment by alidaf** [comment] 2023-09-12 12:53
Has a bug been introduced with the option for :nec|rc5? With a new build I could only get a TSOP4838 to work without any additional parameters. I initially tried with :nec as it is a 38kHz receiver but neither option worked until I removed the option completely.

**Comment by Renber78** [comment] 2023-09-12 16:28
I'm on the latest version (1532) and I use the same IR sensor as you. No problem with both protocols...
gpio=ir or gpio=ir:nec = NEC only
gpio=ir:rc5 = RC5 only

Both protocols are at 38khz and work with the same sensor.

Please note that some old sensors need 5V to function correctly.

I also noticed that when I make a lot of parameter changes on the squeezeESP32 the remote control ends up no longer working, I have to restart the LMS server for it to work.
Maybe you also had this problem during your tests?

**Comment by philippe44** [comment] 2023-09-12 18:16
> Has a bug been introduced with the option for :nec|rc5? With a new build I could only get a TSOP4838 to work without any additional parameters. I initially tried with :nec as it is a 38kHz receiver but neither option worked until I removed the option completely.
>
What syntax did you use *exactly*

**Comment by wizmo2** [comment] 2023-09-15 00:21
(https://github.com/sle118/squeezelite-esp32/commit/c7e4d9711c6c5bc8c13d185734b66d41744c543e) seems to have introduced a problem with RMT initialization.  I'm having a look now, but I get `RMT CHANNEL ERR` during initialization of led_vu with the latest releases.

**Comment by philippe44** [comment] 2023-09-15 00:23
I don't have anything to test unfortunately. The idea was that some RMT parameters must be shared across the system

**Comment by wizmo2** [comment] 2023-09-15 00:32
See the justification.  Will see if I can work out what's happening. May be into the w/e (paying work to do first 😏 )

**Comment by philippe44** [comment] 2023-09-15 00:34
I'll re-read the changes to see if I can spot something as well

**Comment by philippe44** [comment] 2023-09-15 09:50
I think I forgot to set the interrupt, no?

**Comment by Renber78** [comment] 2023-09-16 02:22
I don't know if it's related but it seems that there is a bug with the set_GPIO.

My set_GPIO config:
34=ir:rc5

My log:
```
E (2788) gpio: io_num=34 can only be input
E (2788) gpio: gpio_set_level(237): GPIO output gpio_num error
I (2798) led: Configuring LEDs green:-1 (on:0 rmt:-1 -1% ), red:34 (on:0 rmt:-1 -1% )
```

It looks like he took the GPIO34 also for the red LED... but my remote control works correctly. (I don't have LEDs)

**Comment by philippe44** [comment] 2023-09-16 04:29
Indeed, fixed - good catch, thanks!

**Comment by Renber78** [comment] 2023-09-16 07:23
I still have the same error message with 1552

**Comment by philippe44** [comment] 2023-09-16 07:28
Rebuild is happening now

**Comment by Renber78** [comment] 2023-09-16 07:47
I was too fast ;-)
It actually works now.
THANKS

**Comment by wizmo2** [comment] 2023-09-16 20:19
> I think I forgot to set the interrupt, no?

@philippe44, The interrupt was not the issue with led_vu initialization.  I entered a PR with a fix.

**Closed as completed** 2023-09-24 20:18 UTC
Labels: enhancement

**Comment by Androssboy** [comment] 2024-02-14 18:40
> Повтор обрабатывается. Я не думаю, что у меня есть пульт rc5, все пакеты, которые я получаю, имеют длину 34, то есть NEC или Pronto (AFAIU). Вероятно, ваш пульт тоже не rc5. Я добавил лог, где можно увидеть весь полученный буфер, чтобы можно было разобраться с кодировкой и типом IR.
> 
> Это байтовый дамп, организованный 16-битными пакетами.
> 
> * возьмите 2 байта, LSByte будет первым, поэтому поменяйте их местами
> * 1-й бит (MSbit) — это значение, считываемое ИК-приемником, инвертированное
> * следующие 15 бит — длительность бита в мкс.
> * и так далее...
> 
> Например, при использовании протокола NEC: bb 22 ee 91 равно bb 22 => 22 bb => первый бит равен 0 => 1, длительность 22 bb = 8891 мкс ee 91 => 91 ee => первый бит равен 1 => 0 , длительность 11 ee = 4590 мкс
> 
> Это правильный шаблон заголовка NEC. Для анализа вам может помочь ChatGPT. Что-то вроде: «Возьмите каждый сегмент в шестнадцатеричном формате, соберите их по 2, чтобы сформировать 16-битное значение. Поменяйте местами байты. Возьмите старший бит, инвертируйте его, это значение. Возьмите 15 младших битов, это длительность в мкс». И будьте осторожны, ChatGPT тоже извергает много всякой ерунды.

@philippe44
Dear philippe44!
I'm amazed by your intelligence and skills! Thank you very much for your titanic work.
I'm trying to connect an IR remote control to an ESP32-A1S that has squeezelite-esp32 installed, but I can't succeed. I counted the remote control button codes using Arduino and did everything according to the instructions from the documentation on GIThub.
After carefully reading the forums, I found your message which I quoted at the beginning of this post.
Is this procedure for converting bits and bytes necessary for every remote control and every button? Or is it enough to read the button code using an Arduino sketch and paste it into Slim_Devices_Remote.ir on the LMS server? I'm completely confused...
Please forgive me, but I am not a programmer and I am trying to repeat the project with my own hands. By repeating after you, I myself become smarter!
