### ISSUE TITLE
EPS muse - bluetooth speaker not visible

### ISSUE THREAD

**Issue by Elkropac** [sle118/squeezelite-esp32#210] opened 2022-11-30 12:40 UTC
Hi, i upgraded my espmuse to `fw: Muse.16.2.1241.master-v4.3` and i cannot discover the bluetooth speaker anymore on my phone. It is checked in web interface as enabled

**Comment by sle118** [comment] 2022-11-30 23:05
This is a duplicate of https://github.com/sle118/squeezelite-esp32/issues/207

Please try the most recent release

**Closed as completed by sle118** 2022-11-30 23:05 UTC

**Comment by Elkropac** [comment] 2022-12-01 07:04
Hi, ok i saw this issue, but i thought it's different problem, he tries to connect to remote BT device

**Comment by Elkropac** [comment] 2022-12-01 07:24
With 1250 it seems to work, thanks !

**Comment by daduke** [comment] 2022-12-01 16:09
yes it does! thanks for the quick fix.
